# Generated by Django 3.2.9 on 2021-11-29 01:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15, verbose_name='Категория')),
            ],
        ),
        migrations.RemoveField(
            model_name='products',
            name='category',
        ),
        migrations.AddField(
            model_name='products',
            name='availab',
            field=models.CharField(blank=True, max_length=3, verbose_name='В наличии'),
        ),
        migrations.AlterField(
            model_name='products',
            name='content',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='products',
            name='photo',
            field=models.ImageField(upload_to='photos/%Y/%m/', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='products',
            name='price',
            field=models.CharField(max_length=10, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='products',
            name='sale',
            field=models.CharField(blank=True, max_length=3, verbose_name='Скидка'),
        ),
        migrations.AlterField(
            model_name='products',
            name='title',
            field=models.CharField(max_length=50, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='products',
            name='cat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='main.category'),
        ),
    ]
