# Generated by Django 3.2.9 on 2021-12-02 00:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20211130_1619'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15, verbose_name='Подкатегория')),
                ('slag', models.SlugField(max_length=15, unique=True, verbose_name='URL')),
            ],
        ),
        migrations.AddField(
            model_name='category',
            name='slag',
            field=models.SlugField(max_length=15, null=True, unique=True, verbose_name='URL'),
        ),
        migrations.AddField(
            model_name='products',
            name='subcat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='main.subcategory', verbose_name='Подкатегория'),
        ),
    ]
