# Generated by Django 3.2.9 on 2021-12-02 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20211202_1103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='category',
            name='slag',
            field=models.SlugField(null=True, unique=True, verbose_name='URL'),
        ),
    ]
