# Generated by Django 3.2.9 on 2021-12-02 02:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20211202_1123'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='slag',
            new_name='slug',
        ),
        migrations.RenameField(
            model_name='subcategory',
            old_name='slag',
            new_name='slug',
        ),
    ]
